/**
 * Router action (Tier-1) - High-level intent routing
 * Decides between browser actions vs direct chat response
 * System prompt auto-generated by executor from action description
 */

import { BROWSER_ACTION } from './browser-actions.js';
import { FINAL_RESPONSE } from './final-response-action.js';
import { LLM_TOOL } from './llm-action.js';

export const BROWSER_ROUTER = 'BROWSER_ROUTER';

/**
 * BROWSER_ROUTER action (Tier-1)
 * Routes between browser actions and direct chat responses
 */
export const routerAction = {
  name: BROWSER_ROUTER,
  description: 'Route user requests to browser interaction, general knowledge, or final response',
  input_schema: {
    type: 'object',
    properties: {
      user_message: {
        type: 'string',
        description: 'The user\'s natural language request'
      }
    },
    required: ['user_message'],
    additionalProperties: false
  },
  steps: [
    {
      type: 'llm',
      message: `This is current {{{browser_state}}} 
Goal to fulfill is: 
{{{user_message}}} 

Please choose a tool to fulfill goal, if already fulfilled please choose {{{stop_action}}}`,
      intelligence: 'MEDIUM',
      tool_choice: {
        available_actions: [
          BROWSER_ACTION,
          LLM_TOOL,
          FINAL_RESPONSE
        ],
        stop_action: FINAL_RESPONSE,
        max_iterations: 5
      }
    }
  ]
};
